name: deploy
on:
  workflow_run:
    workflows: [ pre-commit ]
    types: [ completed ]
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: gcp-dingo-den-bots
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4
      - uses: up9cloud/action-rsync@v1.4
        env:
          HOST: ${{ secrets.DEPLOY_HOST }}
          USER: ${{ secrets.DEPLOY_USERNAME }}
          KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          TARGET: discord-bot/
          ARGS_MORE: --exclude='/.env.*' --exclude '/.env'
          POST_SCRIPT: scripts/restart-discord-bot.sh
