name: deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: gcp-dingo-den-bots
    steps:
      - uses: actions/checkout@v2
      - uses: up9cloud/action-rsync@v1.3
        env:
          HOST: ${{ secrets.DEPLOY_HOST }}
          USER: ${{ secrets.DEPLOY_USERNAME }}
          KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          TARGET: discord-dingomata/
          ARGS_MORE: --exclude='/.env.*' --exclude '/.env'
          POST_SCRIPT: scripts/restart-discord-bot.sh
